### ISSUE TITLE
Can I use this yet?

### ISSUE THREAD

**Issue by drd** [browniefed/react-native-flanimatedimage#1]
Just wondering

**Comment by browniefed** [comment]
Accepting pull requests. Unsure how to remove the warning about not using this, I mean it's some seriously good code that I cobbled together. 
This is 100% development ready. It works great in development and especially great with the 2 gifs that I tested it with. Really un-stress tested it! I mean it's render animated gifs 10s of times!

**Comment by browniefed** [comment]
Still no

**Comment by rclai** [comment]
So what exactly is holding you back from considering this production ready?

**Comment by browniefed** [comment]
I don't use react native anymore, I've never put this code into production, this was just for a tutorial, and I don't really know ObjectiveC so it could be production ready however I have no clue.
Feel free to fix it up and release it, I didn't claim the NPM package name.

**Comment by rclai** [comment]
Aw why don't you use it anymore? I've followed a bunch of your tutorials. What do you use now for mobile?

**Comment by browniefed** [comment]
I actually don't do any mobile work anymore unfortunately. I was never a mobile developer, just a front end developer. So I do exclusively web now.

**Comment by nihgwu** [comment]
@browniefed It's so sad to know you don't maintain this package anymore, I've been trapped by the gif stuff for quite a long time https://github.com/facebook/react-native/issues/1968

**Comment by browniefed** [comment]
I'm not saying this won't work, I'm just saying I'm unsure if it's production quality, and or will cover your needs. I'd encourage you to fork it, and explore it for your needs.

This will technically render GIFs through FLAnimatedGif.
