### ISSUE TITLE
Can not get to load

### ISSUE THREAD

**Issue by ninjz** [browniefed/react-native-flanimatedimage#2]
I was excited about this, too bad i can't get this to work and got the following error.
<img width="372" alt="screen shot 2016-02-11 at 10 10 02 pm" src="https://cloud.githubusercontent.com/assets/5641860/12997965/48ee451e-d10c-11e5-96b4-cccf81bf2d31.png">

**Comment by browniefed** [comment]
I'm sure something has changed with the way that React Native does it's bridging and exporting of constants which I believe is what that is referring to.
